# frozen_string_literal: true

require_relative '../tool'
require_relative 'program_support'
require_relative '../../session_length'
require_relative '../../turnarounds'

class Tectonic < Roda
  module MCP
    module Tools
      # Turns one written week into real sessions: a workout per training day, every set
      # pre-created with its warmup ramp, at weights a bar can actually be loaded to.
      #
      # This is the tool that makes a plan a thing the lifter can open. Everything it does
      # is ProgramGenerator's -- the dates, the warmups, the rep conversion, the
      # idempotency on the program day -- so a week generated by an assistant and one
      # generated from the command line are the same rows. Generating a week twice
      # changes nothing, which is what makes this safe to retry.
      class GenerateProgramWeek < Tool
        tool_name 'generate_program_week'
        title 'Write a week of sessions'
        description 'Write one week of a block into real workouts: a session per training ' \
                    'day, warmups included, dated from the block. Defaults to the week ' \
                    'today falls in. Running it again for the same week changes nothing. ' \
                    'Reports about how long each session will take, and says so when one ' \
                    "runs past the block's time budget if it has one."
        scope :write
        input_schema(
          type: 'object',
          properties: { program_id: { type: 'integer' }, week: { type: 'integer' } },
          required: ['program_id'], additionalProperties: false
        )

        def self.perform(context:, arguments:)
          program = ProgramFinder.program(context, arguments[:program_id])
          week = week_for(context, program, arguments[:week])
          workouts = generate(context, program, week)
          lengths = estimate_each(context, program, workouts)
          ok("Week #{week.number} of #{program.name} is scheduled: #{summary(workouts)}." \
             "#{budget_sentence(program, lengths)}",
             structured: payload(program, week, workouts, lengths))
        end

        def self.payload(program, week, workouts, lengths)
          { program_id: program.id, week: week.number,
            time_budget_minutes: program.time_budget_minutes,
            workouts: workouts.map { |workout| Presenter.view_workout(workout) },
            estimated_minutes: lengths.transform_values(&:minutes) }
        end

        # How long each session this call just wrote will take, keyed by workout id. #408.
        #
        # Estimated after generating rather than off the prescription, because the session is
        # what the lifter actually does: the generator adds a warmup ramp the block never
        # wrote, and a ramp is four or five sets with rests between them. Pricing the
        # prescription alone would under-report every barbell day by ten minutes or so, which
        # is exactly the margin a budget is about.
        #
        # Reported whether or not a budget exists, since "Monday is about 92 minutes" is worth
        # knowing on its own and is the number a caller needs to argue with.
        def self.estimate_each(context, program, workouts)
          turnaround = Turnarounds.lookup(program.account_id || context.account_id)
          workouts.to_h do |workout|
            [workout.id, SessionLength.estimate(workout.sets.map(&:values), turnaround:)]
          end
        end

        # The warning #408 asks for, and only when there is a budget to warn against. A block
        # written with no clock in mind must not acquire an opinion about one.
        #
        # It names the overshoot rather than saying a session is too long, and it does not
        # refuse to generate. Whether ninety minutes is wrong is a coaching question -- cut a
        # movement, cut a set, or accept the ninety -- and the app's job is to make the
        # arithmetic visible before the lifter finds it out by running out of time.
        def self.budget_sentence(program, lengths)
          return '' unless program.time_budget_minutes

          over = lengths.values.select { |estimate| estimate.minutes > program.time_budget_minutes }
          return '' if over.empty?

          " #{overshoot(program, over)}"
        end

        def self.overshoot(program, over)
          worst = over.max_by(&:minutes)
          days = over.length == 1 ? 'One session' : "#{over.length} sessions"
          "#{days} in this week #{over.length == 1 ? 'runs' : 'run'} past the " \
            "#{program.time_budget_minutes} minute budget -- the longest is about " \
            "#{worst.minutes} minutes, #{worst.minutes - program.time_budget_minutes} over."
        end

        # Without a week number this means "the week we are in", which is what a lifter
        # asking to be scheduled means; a block that does not cover today has to be told
        # which week, because guessing the nearest one schedules the wrong training.
        def self.week_for(context, program, number)
          return ProgramFinder.week(context, program, number) if number

          program.week_on || raise(Tool::Refusal,
                                   "#{program.name} runs #{program.weeks} week(s) from " \
                                   "#{program.start_date}, which does not cover today. Name a week.")
        end

        # The generator refuses a week it cannot write -- a lift priced as a percentage of
        # a max nothing has been lifted for yet -- by raising with a message written to be
        # read. Left alone it would reach the client as "the tool failed unexpectedly",
        # which tells a model nothing it can act on, so it is re-raised as a refusal.
        def self.generate(context, program, week)
          ProgramGenerator.new(program, created_by: context.application_id).generate(week.number)
        rescue ArgumentError => e
          raise Tool::Refusal, e.message
        end

        def self.summary(workouts)
          workouts.map { |w| "#{w.date.strftime('%a %b %-d')} (#{w.sets.count} sets)" }.join(', ')
        end
      end
    end
  end
end

