# frozen_string_literal: true

require_relative '../tool'
require_relative 'program_support'

class Tectonic < Roda
  module MCP
    module Tools
      # Turns one written week into real sessions: a workout per training day, every set
      # pre-created with its warmup ramp, at weights a bar can actually be loaded to.
      #
      # This is the tool that makes a plan a thing the lifter can open. Everything it does
      # is ProgramGenerator's -- the dates, the warmups, the rep conversion, the
      # idempotency on the program day -- so a week generated by an assistant and one
      # generated from the command line are the same rows. Generating a week twice
      # changes nothing, which is what makes this safe to retry.
      class GenerateProgramWeek < Tool
        tool_name 'generate_program_week'
        description 'Write one week of a block into real workouts: a session per training ' \
                    'day, warmups included, dated from the block. Defaults to the week ' \
                    'today falls in. Running it again for the same week changes nothing.'
        scope :write
        input_schema(
          type: 'object',
          properties: { program_id: { type: 'integer' }, week: { type: 'integer' } },
          required: ['program_id'], additionalProperties: false
        )

        def self.perform(context:, arguments:)
          program = ProgramFinder.program(context, arguments[:program_id])
          week = week_for(context, program, arguments[:week])
          workouts = generate(context, program, week)
          ok("Week #{week.number} of #{program.name} is scheduled: #{summary(workouts)}.",
             structured: { program_id: program.id, week: week.number,
                           workouts: workouts.map { |workout| Presenter.view_workout(workout) } })
        end

        # Without a week number this means "the week we are in", which is what a lifter
        # asking to be scheduled means; a block that does not cover today has to be told
        # which week, because guessing the nearest one schedules the wrong training.
        def self.week_for(context, program, number)
          return ProgramFinder.week(context, program, number) if number

          program.week_on || raise(Tool::Refusal,
                                   "#{program.name} runs #{program.weeks} week(s) from " \
                                   "#{program.start_date}, which does not cover today. Name a week.")
        end

        # The generator refuses a week it cannot write -- a lift priced as a percentage of
        # a max nothing has been lifted for yet -- by raising with a message written to be
        # read. Left alone it would reach the client as "the tool failed unexpectedly",
        # which tells a model nothing it can act on, so it is re-raised as a refusal.
        def self.generate(context, program, week)
          ProgramGenerator.new(program, created_by: context.application_id).generate(week.number)
        rescue ArgumentError => e
          raise Tool::Refusal, e.message
        end

        def self.summary(workouts)
          workouts.map { |w| "#{w.date.strftime('%a %b %-d')} (#{w.sets.count} sets)" }.join(', ')
        end
      end
    end
  end
end

